### PR TITLE
New concurrent model

### PR DESCRIPTION
**Pull request by Liastre**
Proper concurrent model for minitrace

### CODE REVIEW

**Comment by Liastre** [comment]
@hrydgard hello. Any update on this?

**Comment by mcourteaux** [comment]
I'm using this branch, and it works great!

**Comment by hrydgard** [comment]
Apologies, I haven't taken the time to review this. Have a lot on my plate.

It does look good to me - let's go for it.

**Comment by Liastre** [comment]
Hey @mcourteaux, there was separate thread with discussion https://github.com/hrydgard/minitrace/pull/17 you might want to take a look. In short, there was issue, since minitrace used a single buffer for collecting messages, so when we flushing buffer it locking itself till flush all the events, in case you have huge amount of events there some lags and delays appears. Also flushing events method was not threadsafe.

**Comment by Liastre** [comment]
@hrydgard thanks for merging it finally :)

**Pull request merged**
